sudo: required
services:
  - docker
dist: bionic
env:
  global:
    - DOCKER_IMAGE=lbracun/tempo-detection-ms:1.0-${TRAVIS_JOB_NUMBER}
script:
  - docker build -t "$DOCKER_IMAGE" .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
